### PR TITLE
FIX: The input does not focus, on click of new message button in top right corner

### LINKED ISSUE #1: The input does not focus, on click of new message button in  top right corner
Screenshot 2024-06-06 at 6 39 22 PM

On Click of new message (pencil edit icon) button in top right corner, all this should happen:
- The message input should get focused (cursor should blink and in mobile devices keyboard should open).
- All messages should be cleared from state.
- API call should be cancelled if any in progress.

The first point is not happening, please fix this!

### PR DESCRIPTION
**Pull request by robGardiner01**
fixes #1

### CODE REVIEW

**Comment by anish-work** [comment]
@robGardiner01 I don't it works properly, can you try again with latest code pulled in ?

**Comment by robGardiner01** [comment]
Works for me. Am I right in thinking the only issue is that the input text box should focus when you click the pencil icon?

**Comment by anish-work** [comment]
> Works for me. Am I right in thinking the only issue is that the input text box should focus when you click the pencil icon?

yes thats what we want here

**Comment by robGardiner01** [comment]
That's what it does for me. When I click the pencil icon, it focuses on the input box and lets me type in it. What happens when you press it?

**Comment by anish-work** [comment]
> That's what it does for me. When I click the pencil icon, it focuses on the input box and lets me type in it. What happens when you press it?

Well, I see the focus is happening but when the thing is embeded in "popup" or "fullscreen" mode it still doesn't work !

**Comment by robGardiner01** [comment]
That should be it fixed. The button was disabled so wasn't working when clicking it

**Comment by anish-work** [comment]
> That should be it fixed. The button was disabled so wasn't working when clicking it

No the button gets enabled when there is at least 1 message in the chat. So we need the disabled button back

**Comment by robGardiner01** [comment]
Does that work for you? When I enter a message in the chat the button is still disabled

**Comment by robGardiner01** [comment]
Never mind, I realise now what you meant by message in the chat! That should be it working now I hope

**Pull request merged**
